### ISSUE TITLE
Low Performance Mode

### ISSUE THREAD

**Issue by TheForeverLoneWolf** [WatercressStudios/website#29]
I'd love to have a toggleable low-performance mode - removing animations like the roller, the twinkling stars, the opening of the hamburger menu, the flipping of member cards, etc.

**Comment by Happiness-plus** [comment]
@TheForeverLoneWolf safari is low-performance mode honey. I will have that done next week. Do you know anyone with an iphone to help me test?

**Comment by TheForeverLoneWolf** [comment]
We should have low performance mode as an option, not just something that works only on Safari - it should have the option for low performance mode on PC/Desktop as well.  I don't have an iPhone, but reach out to Kyle, he might have/know someone. Ask around on Discord if all else fails.

**Comment by Happiness-plus** [comment]
@TheForeverLoneWolf the problem is that we can't do that because of our current architecture. It's similar to that of having a full blown accessibility mode. I can't trigger it. I got lucky on how to trigger stuff exclusively for safari but I can't do that because I don't know what a "performance mode" would entail besides a normal series of optimizations prerelease. ￼
